# This file defines the services for your application.
# Running 'docker compose up' from the same directory will build
# and run all these services together.
version: '3.8'

services:
  # The 'frontend' service is your React application.
  frontend:
    # Use the Dockerfile in the 'frontend' directory to build the image.
    build:
      context: ./frontend
    # Map port 3000 on your host machine to port 80 in the container,
    # which is where Nginx serves the app.
    ports:
      - "3000:80"
    # This ensures the frontend doesn't start until the backend is ready.
    depends_on:
      - backend

  # The 'backend' service is your Node.js Express server.
  backend:
    # Use the Dockerfile in the 'backend' directory to build the image.
    build:
      context: ./backend
    # Map port 5001 on your host machine to port 5001 in the container.
    ports:
      - "5001:5001"
    